[New Model] Notification Header 1.0.0 (Shared Aspect Model)
eclipse-tractusx/sldt-semantic-models pull request #128
Opened 2023-03-28 16:09 UTC by sschul33

initial model

## Description

 -->

Closes #115 

## MS2 Criteria
(to be filled out by PR reviewer)
- [x] the model **validates** with the BAMM SDS SDK in the version specified in the Readme.md of this repository by the time of the MS2 check  (e.g., 'java -jar bamm-cli.jar -i \<path-to-aspect-model\> -v ). The  BAMM CLI is available [here](https://openmanufacturingplatform.github.io/sds-documentation/sds-developer-guide/dev-snapshot/tooling-guide/bamm-cli.html) and in [GitHub](https://github.com/OpenManufacturingPlatform/sds-sdk/releases)
- [x] use **Camel-Case** (e.g., "MyModelElement" or "TimeDifferenceGmtId", when in doubt follow https://google.github.io/styleguide/javaguide.html#s5.3-camel-case)
- [x] the identifiers for all model elements **start with a capital letter** except for properties
- [x] the identifier for **properties starts with a small letter**
- [ ] all model elements **at least contain the fields "name" and "description"** in English language. 
- [x] **no duplicate names or preferredNames** within an Aspect (e.g. a Property and the referenced Characteristic should not have the same name)
- [ ] the versioning in the URN **follows semantic versioning**, where minor version bumps are backwards compatible and major version bumps are not backwards compatible. 
- [x] use **abbreviations only when necessary** and if these are sufficiently common
- [x] **avoid redundant prefixes in property names** (consider adding properties to an enclosing Entity or even adapt the namespace of the model elements, e.g., instead of having two properties `DismantlerId` and `DismantlerName` use an Entity `Dismantler` with the properties `name` and `id` or use a URN like `io.catenax.dismantler:0.0.1`)
- [x] fields `preferredName` and `description` are not the same
- [ ] **`preferredName` should be human readable** and follow normal orthography (e.g., no camel case but normal word separation)
- [x] name of aspect is singular except if it only has one property which is a Collection, List or Set. In theses cases, the aspect name is plural.
- [x] units are referenced from the BAMM unit catalog whenever possible
- [x] **use constraints** to make known constraints from the use case explicit in the aspect model 
- [x] when relying on **external standards**, they are referenced through a **"see"** element
- [x] all properties with an [simple type](https://openmanufacturingplatform.github.io/sds-documentation/bamm-specification/v1.0.0/datatypes.html) have an example value
- [x] metadata.json exists with status "release"
- [x] file RELEASE_NOTES.md exists and contains entries for proposed model changes 

## MS3 Criteria
(to be filled out by semantic modeling team before merge to main-branch)
- [ ] All required reviewers have approved this PR (see reviewers section)
- [ ] The new aspect (version) will be implemented by at least one data provider
- [ ] The new aspect (version) will be consumed by at least one data consumer
- [ ] There exists valid test data
- [ ] In case of a new (incompatible) major version to an existing version, a migration strategy has been developed
- [ ] The model has at least version '1.0.0'

2023-03-28 16:10 UTC, sschul33 commented
@bs-jokri : Please review
@jacewski-bosch , @BenediktMuellerIML : FYI

2023-04-03 13:32 UTC, sschul33 commented
Modeling_Team

2023-04-20 08:55 UTC, bs-jokri requested changes
check comments

2023-04-20 08:55 UTC, bs-jokri commented on io.catenax.notification_header/1.0.0/NotificationHeader.ttl
> +    bamm:preferredName "header"@en;
uppercase

2023-04-20 08:55 UTC, bs-jokri commented on io.catenax.notification_header/1.0.0/NotificationHeader.ttl
> +    bamm:name "BpnCharacteristic";
pref name and description missing

2023-04-20 08:55 UTC, bs-jokri commented on io.catenax.notification_header/1.0.0/NotificationHeader.ttl
> +:UuidCharacteristic a bamm:Characteristic;
description missing

2023-04-20 08:55 UTC, bs-jokri commented on io.catenax.notification_header/1.0.0/NotificationHeader.ttl
> +:UrlCharacteristic a bamm:Characteristic;
description

2023-04-20 08:55 UTC, bs-jokri commented on io.catenax.notification_header/1.0.0/NotificationHeader.ttl
> +:ReplyAssetIdCharacteristic a bamm:Characteristic;
description

2023-04-20 08:55 UTC, bs-jokri commented on io.catenax.notification_header/1.0.0/NotificationHeader.ttl
> +    bamm:description "a UUID v4 that identifies the message in relation to which this message is sent; MUST be omitted if no such relation exists"@en;
start uppercase

2023-04-20 08:55 UTC, bs-jokri commented on io.catenax.notification_header/1.0.0/NotificationHeader.ttl
> +    bamm:preferredName "notificationType"@en;
standard English

2023-04-20 08:55 UTC, bs-jokri commented on io.catenax.notification_header/1.0.0/NotificationHeader.ttl
> +    bamm:description "the standardized schema identifier of the message document in the content property"@en;
start uppercase

2023-04-20 08:55 UTC, bs-jokri commented on io.catenax.notification_header/1.0.0/NotificationHeader.ttl
> +    bamm:name "NotificationTypeCharacteristic";
description missing

2023-07-06 17:49 UTC, bs-jokri commented
replaced by https://github.com/eclipse-tractusx/sldt-semantic-models/pull/227

2023-07-06 17:49 UTC, closed without merging