[New Model] Product Stock
eclipse-tractusx/sldt-semantic-models pull request #154
Opened 2023-04-24 11:11 UTC by tom-rm-meyer-ISST

## Description
This is the draft version for #145.

**Things to discuss:**
- materialNumberDataSpace: This shall be an optional reference to the PartAsPlanned. It should be aligend according to issue #103 - Therefore the data type is definetly wrong
- Location Entity: 
  - this should allow BPNS and BPNA (depending on how BPDM continues), should we add a trait to restrict the key type?
  - should we somewhat rename it to locationId?
  - should we set the see to the CX standard and if so, where?

Closes #145 

## MS2 Criteria
(to be filled out by PR reviewer)
- [ ] the model **validates** with the BAMM SDS SDK in the version specified in the Readme.md of this repository by the time of the MS2 check  (e.g., 'java -jar bamm-cli.jar -i \<path-to-aspect-model\> -v ). The  BAMM CLI is available [here](https://openmanufacturingplatform.github.io/sds-documentation/sds-developer-guide/dev-snapshot/tooling-guide/bamm-cli.html) and in [GitHub](https://github.com/OpenManufacturingPlatform/sds-sdk/releases)
- [ ] use **Camel-Case** (e.g., "MyModelElement" or "TimeDifferenceGmtId", when in doubt follow https://google.github.io/styleguide/javaguide.html#s5.3-camel-case)
- [ ] the identifiers for all model elements **start with a capital letter** except for properties
- [ ] the identifier for **properties starts with a small letter**
- [ ] all model elements **at least contain the fields "name" and "description"** in English language. 
- [ ] **no duplicate names or preferredNames** within an Aspect (e.g. a Property and the referenced Characteristic should not have the same name)
- [ ] the versioning in the URN **follows semantic versioning**, where minor version bumps are backwards compatible and major version bumps are not backwards compatible. 
- [ ] use **abbreviations only when necessary** and if these are sufficiently common
- [ ] **avoid redundant prefixes in property names** (consider adding properties to an enclosing Entity or even adapt the namespace of the model elements, e.g., instead of having two properties `DismantlerId` and `DismantlerName` use an Entity `Dismantler` with the properties `name` and `id` or use a URN like `io.catenax.dismantler:0.0.1`)
- [ ] fields `preferredName` and `description` are not the same
- [ ] **`preferredName` should be human readable** and follow normal orthography (e.g., no camel case but normal word separation)
- [ ] name of aspect is singular except if it only has one property which is a Collection, List or Set. In theses cases, the aspect name is plural.
- [ ] units are referenced from the BAMM unit catalog whenever possible
- [ ] **use constraints** to make known constraints from the use case explicit in the aspect model 
- [ ] when relying on **external standards**, they are referenced through a **"see"** element
- [ ] all properties with an [simple type](https://openmanufacturingplatform.github.io/sds-documentation/bamm-specification/v1.0.0/datatypes.html) have an example value
- [ ] metadata.json exists with status "release"
- [ ] file RELEASE_NOTES.md exists and contains entries for proposed model changes 
- [ ] all contributors to this model are mentioned in copyright header of model file

## MS3 Criteria
(to be filled out by semantic modeling team before merge to main-branch)
- [ ] All required reviewers have approved this PR (see reviewers section)
- [ ] The new aspect (version) will be implemented by at least one data provider
- [ ] The new aspect (version) will be consumed by at least one data consumer
- [ ] There exists valid test data
- [ ] In case of a new (incompatible) major version to an existing version, a migration strategy has been developed
- [ ] The model has at least version '1.0.0'

2023-04-24 14:17 UTC, tom-rm-meyer-ISST commented
Modelling_Team

2023-05-02 11:14 UTC, bs-jokri requested changes

2023-05-02 11:14 UTC, bs-jokri commented on io.catenax.product_stock/1.0.0/metadata.json
> +{ status : draft }
needs to be changed to release

2023-05-02 11:37 UTC, bs-jokri requested changes

2023-05-02 11:37 UTC, bs-jokri commented on io.catenax.product_stock/1.0.0/ProductStock.ttl
> +    bamm:see <urn:uri:CX-0010>.
same here. please check all the see elements and change to a proper uri (eg URL)

2023-05-02 11:37 UTC, bs-jokri commented on io.catenax.product_stock/1.0.0/ProductStock.ttl
> +    bamm:preferredName "ID value for specific Locatio"@en;
quite a long name. also fix Locatio to Location

2023-05-02 11:37 UTC, bs-jokri commented on io.catenax.product_stock/1.0.0/ProductStock.ttl
> +    bamm:preferredName "ype of specific Location ID"@en;
ype -> Type

2023-05-02 11:37 UTC, bs-jokri commented on io.catenax.product_stock/1.0.0/ProductStock.ttl
> +    bamm:preferredName "Stock allocated to Customer"@en;
check for consistent upper case writing in all preferredName tags. Sometimes you write lower case in the first character sometimes uppercase. I would opt for headline writing with uppercase writing of important words

2023-05-15 13:14 UTC, bs-jokri commented
@tom-rm-meyer-ISST is there an update on the see topic?

2023-05-15 14:10 UTC, tom-rm-meyer-ISST commented
> @tom-rm-meyer-ISST is there an update on the see topic?

No update by standardization team. Sent a friendly reminder.

From my point of view, we could resolve it here and update it with a patch later on.

2023-05-15 14:41 UTC, bs-jokri commented
From MS3 review: materialNumberCustomer description needs to be adjusted to reflect that in some cases also the material number of the supplier can be used.

2023-05-31 12:30 UTC, petyog commented
...
> Test data needs to be provided

A test data set can be provided upon request . Here is an example / snippet:
```json
{

  "materialNumberDataSpace" : "48878d48-6f1d-47f5-8ded-a441d0d879df",

  "materialNumberCustomer" : "MNR-7307-AU340474.002",

  "materialNumberSupplier" : "MNR-8101-ID146955.001",

  "positions" : [ {

    "lastUpdatedOnDate" : "2023-04-01T14:23:00.66372+01:00",

    "orderPositionReference" : {

      "supplierOrderId" : "M-Nbr-4711",

      "customerOrderId" : "C-Nbr-4711",

      "customerOrderPositionId" : "PositionId-01"

    },

    "allocatedStocks" : [ {

      "quantityOnAllocatedStock" : {

        "quantityNumber" : 2.5,

        "measurementUnit" : "unit:litre"

      },

      "supplierStockLocation" : {

        "locationKeyType" : "BPNS",

        "locationKeyValue" : "BPNS0123456789ZZ"

      }

    } ]

  } ]

}
```

2023-06-04 21:37 UTC, petyog commented
@bs-jokri please don't merge the PR yet. There are still pending changes (the names of few fields must be streamlined). The team will get back to you once ready.

2023-06-05 13:39 UTC, petyog commented
@bs-jokri turned out that there are no pending changes. The PR can be merged.

2023-06-05 14:35 UTC, bs-jokri approved these changes

2023-06-05 14:45 UTC, merged