Serial part 1.0.0 renaming
eclipse-tractusx/sldt-semantic-models pull request #186
Opened 2023-05-29 20:45 UTC by jacewski-bosch

## Description

We want to create a new model named SerialPartAsBuilt which will replace the existing model SerialPartTypization. The reason for the replacement is to match our naming convention from BomAsPlanned and other BoMs.

Closes #79 

## MS2 Criteria
(to be filled out by PR reviewer)
- [ ] the model **validates** with the BAMM SDS SDK in the version specified in the Readme.md of this repository by the time of the MS2 check  (e.g., 'java -jar bamm-cli.jar -i \<path-to-aspect-model\> -v ). The  BAMM CLI is available [here](https://openmanufacturingplatform.github.io/sds-documentation/sds-developer-guide/dev-snapshot/tooling-guide/bamm-cli.html) and in [GitHub](https://github.com/OpenManufacturingPlatform/sds-sdk/releases)
- [ ] use **Camel-Case** (e.g., "MyModelElement" or "TimeDifferenceGmtId", when in doubt follow https://google.github.io/styleguide/javaguide.html#s5.3-camel-case)
- [ ] the identifiers for all model elements **start with a capital letter** except for properties
- [ ] the identifier for **properties starts with a small letter**
- [ ] all model elements **at least contain the fields "name" and "description"** in English language. 
- [ ] **no duplicate names or preferredNames** within an Aspect (e.g. a Property and the referenced Characteristic should not have the same name)
- [ ] the versioning in the URN **follows semantic versioning**, where minor version bumps are backwards compatible and major version bumps are not backwards compatible. 
- [ ] use **abbreviations only when necessary** and if these are sufficiently common
- [ ] **avoid redundant prefixes in property names** (consider adding properties to an enclosing Entity or even adapt the namespace of the model elements, e.g., instead of having two properties `DismantlerId` and `DismantlerName` use an Entity `Dismantler` with the properties `name` and `id` or use a URN like `io.catenax.dismantler:0.0.1`)
- [ ] fields `preferredName` and `description` are not the same
- [ ] **`preferredName` should be human readable** and follow normal orthography (e.g., no camel case but normal word separation)
- [ ] name of aspect is singular except if it only has one property which is a Collection, List or Set. In theses cases, the aspect name is plural.
- [ ] units are referenced from the BAMM unit catalog whenever possible
- [ ] **use constraints** to make known constraints from the use case explicit in the aspect model 
- [ ] when relying on **external standards**, they are referenced through a **"see"** element
- [ ] all properties with an [simple type](https://openmanufacturingplatform.github.io/sds-documentation/bamm-specification/v1.0.0/datatypes.html) have an example value
- [ ] metadata.json exists with status "release"
- [ ] file RELEASE_NOTES.md exists and contains entries for proposed model changes 
- [ ] all contributors to this model are mentioned in copyright header of model file

## MS3 Criteria
(to be filled out by semantic modeling team before merge to main-branch)
- [ ] All required reviewers have approved this PR (see reviewers section)
- [ ] The new aspect (version) will be implemented by at least one data provider
- [ ] The new aspect (version) will be consumed by at least one data consumer
- [ ] There exists valid test data
- [ ] In case of a new (incompatible) major version to an existing version, a migration strategy has been developed
- [ ] The model has at least version '1.0.0'

2023-05-31 09:02 UTC, bs-jokri requested changes
please add release notes and check comment

2023-05-31 09:02 UTC, bs-jokri commented on io.catenax.serial_part/1.0.0/SerialPart.ttl
> +   samm:see <http://private.pdm-if.org/web/pdm-if/recommended-practices1> ;
Url don't seem to be accessible

2023-05-31 09:02 UTC, bs-jokri requested changes
please add release notes and check comment

2023-06-01 09:57 UTC, jacewski-bosch commented on io.catenax.serial_part/1.0.0/metadata.json
> +{ "status" : "release"}
done.

2023-06-05 10:49 UTC, jacewski-bosch commented on io.catenax.serial_part/1.0.0/SerialPart.ttl
> +   samm:see <http://private.pdm-if.org/web/pdm-if/recommended-practices1> ;
fixed.

2023-06-12 13:48 UTC, jacewski-bosch commented
modeling_team

2023-06-12 14:10 UTC, bs-jokri approved these changes
LGTM

2023-06-13 10:10 UTC, BirgitBoss commented
I think the Characteristic of ManufacutringCharateristic should be "SingleEntity"
I think the Characteristic of PartTypeInformationCharacteristic should be "SingleEntity"
For the string Characteristics you should consider to use the predefined characteristics "Text" or the characteristic "Code"

2023-06-14 10:13 UTC, bs-jokri approved these changes
LGTM

2023-06-14 10:13 UTC, merged