Adding first version of the manufacturing capability aspect model.
eclipse-tractusx/sldt-semantic-models pull request #189
Opened 2023-06-01 06:48 UTC by FlorianPatzerFraunhoferIOSB

## Description
This PR introduces the first version (1.0.0) of the manufacturing capability aspect model.

Refers to #158 

## MS2 Criteria
(to be filled out by PR reviewer)
- [ ] the model **validates** with the BAMM SDS SDK in the version specified in the Readme.md of this repository by the time of the MS2 check  (e.g., 'java -jar bamm-cli.jar -i \<path-to-aspect-model\> -v ). The  BAMM CLI is available [here](https://openmanufacturingplatform.github.io/sds-documentation/sds-developer-guide/dev-snapshot/tooling-guide/bamm-cli.html) and in [GitHub](https://github.com/OpenManufacturingPlatform/sds-sdk/releases)
- [ ] use **Camel-Case** (e.g., "MyModelElement" or "TimeDifferenceGmtId", when in doubt follow https://google.github.io/styleguide/javaguide.html#s5.3-camel-case)
- [ ] the identifiers for all model elements **start with a capital letter** except for properties
- [ ] the identifier for **properties starts with a small letter**
- [ ] all model elements **at least contain the fields "name" and "description"** in English language. 
- [ ] **no duplicate names or preferredNames** within an Aspect (e.g. a Property and the referenced Characteristic should not have the same name)
- [ ] the versioning in the URN **follows semantic versioning**, where minor version bumps are backwards compatible and major version bumps are not backwards compatible. 
- [ ] use **abbreviations only when necessary** and if these are sufficiently common
- [ ] **avoid redundant prefixes in property names** (consider adding properties to an enclosing Entity or even adapt the namespace of the model elements, e.g., instead of having two properties `DismantlerId` and `DismantlerName` use an Entity `Dismantler` with the properties `name` and `id` or use a URN like `io.catenax.dismantler:0.0.1`)
- [ ] fields `preferredName` and `description` are not the same
- [ ] **`preferredName` should be human readable** and follow normal orthography (e.g., no camel case but normal word separation)
- [ ] name of aspect is singular except if it only has one property which is a Collection, List or Set. In theses cases, the aspect name is plural.
- [ ] units are referenced from the BAMM unit catalog whenever possible
- [ ] **use constraints** to make known constraints from the use case explicit in the aspect model 
- [ ] when relying on **external standards**, they are referenced through a **"see"** element
- [ ] all properties with an [simple type](https://openmanufacturingplatform.github.io/sds-documentation/bamm-specification/v1.0.0/datatypes.html) have an example value
- [ ] metadata.json exists with status "release"
- [ ] file RELEASE_NOTES.md exists and contains entries for proposed model changes 
- [ ] all contributors to this model are mentioned in copyright header of model file

## MS3 Criteria
(to be filled out by semantic modeling team before merge to main-branch)
- [ ] All required reviewers have approved this PR (see reviewers section)
- [ ] The new aspect (version) will be implemented by at least one data provider
- [ ] The new aspect (version) will be consumed by at least one data consumer
- [ ] There exists valid test data
- [ ] In case of a new (incompatible) major version to an existing version, a migration strategy has been developed
- [ ] The model has at least version '1.0.0'

2023-06-14 09:22 UTC, FlorianPatzerFraunhoferIOSB commented
@bs-jokri Changes made as discussed: ede247f6dfb43040eb80f415ef641a4bce624648

2023-06-16 10:13 UTC, bs-jokri requested changes
please check my comments

2023-06-19 07:51 UTC, FlorianPatzerFraunhoferIOSB commented on io.catenax.manufacturing_capability/1.0.0/ManufacturingCapability.ttl
> +@prefix bamm: <urn:bamm:io.openmanufacturing:meta-model:2.0.0#> .
Done

2023-06-19 07:52 UTC, FlorianPatzerFraunhoferIOSB commented on io.catenax.manufacturing_capability/1.0.0/ManufacturingCapability.ttl
> +   bamm:description "An aspect model representing manufacturing capabilities, based on the concepts for products, processes, resources and capabilities, as well as their relations to eachother."@en ;
Done

2023-06-19 11:35 UTC, bs-jokri requested changes
please check comment

2023-06-19 11:35 UTC, bs-jokri commented on io.catenax.manufacturing_capability/1.0.0/ManufacturingCapability.ttl
> +#
add 
# Copyright (c) 2022 Contributors to the Eclipse Foundation

for single contributions not covered by explicit mentions

2023-06-19 11:39 UTC, FlorianPatzerFraunhoferIOSB commented on io.catenax.manufacturing_capability/1.0.0/ManufacturingCapability.ttl
> +#
Done

2023-06-26 12:38 UTC, bs-jokri approved these changes
lgtm

2023-07-03 13:58 UTC, bs-jokri commented
from MS3 review
adjust date of rlease notes to date of MS3 approval
```
# [1.0.0] - 2023-06-14
```
to
```
# [1.0.0] - 2023-07-03
```

2023-07-03 14:46 UTC, FlorianPatzerFraunhoferIOSB commented
Updated Release Notes date to 2023-07-03

2023-07-04 14:05 UTC, merged