created first version of getShopfloorInformationAspect
eclipse-tractusx/sldt-semantic-models pull request #235
Opened 2023-07-07 12:34 UTC by wehrstedt-jan

## Description

 -->

Closes #229

use of header of https://github.com/eclipse-tractusx/sldt-semantic-models/pull/227 required

## MS2 Criteria
(to be filled out by PR reviewer)
- [ ] the model **validates** with the BAMM SDS SDK in the version specified in the Readme.md of this repository by the time of the MS2 check  (e.g., 'java -jar bamm-cli.jar -i \<path-to-aspect-model\> -v ). The  BAMM CLI is available [here](https://openmanufacturingplatform.github.io/sds-documentation/sds-developer-guide/dev-snapshot/tooling-guide/bamm-cli.html) and in [GitHub](https://github.com/OpenManufacturingPlatform/sds-sdk/releases)
- [ ] use **Camel-Case** (e.g., "MyModelElement" or "TimeDifferenceGmtId", when in doubt follow https://google.github.io/styleguide/javaguide.html#s5.3-camel-case)
- [ ] the identifiers for all model elements **start with a capital letter** except for properties
- [ ] the identifier for **properties starts with a small letter**
- [ ] all model elements **at least contain the fields "preferred name" and "description"** in English language. The description must be comprehensible. It is not required to write full sentences but style should be consistent over the whole model
- [ ] Property and the referenced Characteristic should not have the same name
- [ ] the versioning in the URN **follows semantic versioning**, where minor version bumps are backwards compatible and major version bumps are not backwards compatible. 
- [ ] use **abbreviations only when necessary** and if these are sufficiently common
- [ ] **avoid redundant prefixes in property names** (consider adding properties to an enclosing Entity or even adapt the namespace of the model elements, e.g., instead of having two properties `DismantlerId` and `DismantlerName` use an Entity `Dismantler` with the properties `name` and `id` or use a URN like `io.catenax.dismantler:0.0.1`)
- [ ] fields `preferredName` and `description` are not the same
- [ ] **`preferredName` should be human readable** and follow normal orthography (e.g., no camel case but normal word separation)
- [ ] name of aspect is singular except if it only has one property which is a Collection, List or Set. In theses cases, the aspect name is plural.
- [ ] units are referenced from the BAMM unit catalog whenever possible
- [ ] **use constraints** to make known constraints from the use case explicit in the aspect model 
- [ ] when relying on **external standards**, they are referenced through a **"see"** element
- [ ] all properties with an [simple type](https://openmanufacturingplatform.github.io/sds-documentation/bamm-specification/v1.0.0/datatypes.html) have an example value
- [ ] metadata.json exists with status "release"
- [ ] generated json schema validates against example json payload
- [ ] file RELEASE_NOTES.md exists and contains entries for proposed model changes 
- [ ] all contributors to this model are mentioned in copyright header of model file

## MS3 Criteria
(to be filled out by semantic modeling team before merge to main-branch)
- [ ] All required reviewers have approved this PR (see reviewers section)
- [ ] The new aspect (version) will be implemented by at least one data provider
- [ ] The new aspect (version) will be consumed by at least one data consumer
- [ ] There exists valid test data
- [ ] In case of a new (incompatible) major version to an existing version, a migration strategy has been developed
- [ ] The model has at least version '1.0.0'
- [ ] The release date in the Release Note is set to the date of the MS3 approval

2023-07-11 10:46 UTC, bs-jokri requested changes
please check my comments

2023-07-11 15:28 UTC, bs-jokri requested changes

2023-07-11 15:28 UTC, bs-jokri commented on io.catenax.mp_standard_request/1.0.0/GetShopfloorInformation.ttl
> +:CXHeaderCharacteristic a samm:Characteristic ;
you can import the characteristic directly or even the property, if it fits

2023-07-13 21:56 UTC, bs-jokri requested changes
please check my comments

2023-07-13 21:56 UTC, bs-jokri commented on io.catenax.mp_standard_request/1.0.0/ShopfloorInformationTypes.ttl
> +   samm-c:values ( "Month" "Day" "Week" "Hour" "Minute" "Second" ) .
consider referencing UNECE units of the SAMM unit catalog by referencing them via xsd:curie 
https://eclipse-esmf.github.io/samm-specification/2.0.0/appendix/unitcatalog.html

eg "unit:hour"^^xsd:curie

2023-07-14 20:44 UTC, bs-jokri commented
@wehrstedt-jan what you could think about is to adjust the name to
io.catenax.shopfloor_information.production_forecast/10.0/ProductionForecast.ttl

As all other models are describing an object as such and not an action. This comment is not hindering ms2 but might be considered in the CTSM discussion for MS3 approval

2023-07-14 20:52 UTC, bs-jokri approved these changes
Minor comments. Should be resolved prior release

2023-07-14 20:52 UTC, bs-jokri commented on io.catenax.shopfloor_information.get_production_forecast/1.0.0/GetProductionForecast.ttl
> +   samm:description "Data model for a  request"@en ;
not sure if there is a additional whitespace. If so remove.

2023-07-14 20:52 UTC, bs-jokri commented on io.catenax.shopfloor_information.get_production_forecast/1.0.0/GetProductionForecast.ttl
> +   samm:description "DataType for a request"@en ;
Data type

2023-07-14 20:52 UTC, bs-jokri commented on io.catenax.shopfloor_information.get_production_forecast/1.0.0/GetProductionForecast.ttl
> +   samm:description "Boolean variable that detemines whether the customer request information about each position of an order, or information about the complete order"@en ;
omit comma

2023-07-14 20:52 UTC, bs-jokri commented on io.catenax.shopfloor_information.get_production_forecast/1.0.0/GetProductionForecast.ttl
> +   samm:preferredName "TimeValueCharacteristic"@en ;
no camel case normal orthography

2023-07-14 20:52 UTC, bs-jokri commented on io.catenax.shopfloor_information.get_production_forecast/RELEASE_NOTES.md
> +## [1.0.0]
add date of mS3 approval as soon as it is available

2023-07-14 20:52 UTC, bs-jokri commented on io.catenax.shopfloor_information.get_production_forecast/1.0.0/GetProductionForecast.ttl
> +@prefix ext-header: <urn:samm:io.catenax.message_header:1.0.0#> .
it could be that this model will be moved to the namespace
io.catenax.shared.message_header:1.0.0
adjust that, if this is the case

2023-07-14 20:53 UTC, bs-jokri commented
MS2 approval given with the condition that the model io.catenax.message_header:1.0.0 is released (otherwise model cannot validate)

2023-07-17 14:46 UTC, bosserf commented
MS3 Criteria
(to be filled out by semantic modeling team before merge to main-branch)

All required reviewers have approved this PR (see reviewers section) -> OK
The new aspect (version) will be implemented by at least one data provider -> OK
The new aspect (version) will be consumed by at least one data consumer -> OK
There exists valid test data -> OK
In case of a new (incompatible) major version to an existing version, a migration strategy has been developed -> doesn't apply
The model has at least version '1.0.0' -> OK
The release date in the Release Note is set to the date of the MS3 approval -> has to be done

2023-07-17 14:46 UTC, bosserf commented
MS3: approval given with the condition that the model io.catenax.message_header:1.0.0 is released (otherwise model cannot validate)
otherwise approved by group

2023-09-25 13:06 UTC, merged