first version of UnsubscribeShopfloorInformation
eclipse-tractusx/sldt-semantic-models pull request #237
Opened 2023-07-07 12:49 UTC by wehrstedt-jan

## Description

 -->

Closes #232

requires use of header https://github.com/eclipse-tractusx/sldt-semantic-models/pull/227 

## MS2 Criteria
(to be filled out by PR reviewer)
- [ ] the model **validates** with the BAMM SDS SDK in the version specified in the Readme.md of this repository by the time of the MS2 check  (e.g., 'java -jar bamm-cli.jar -i \<path-to-aspect-model\> -v ). The  BAMM CLI is available [here](https://openmanufacturingplatform.github.io/sds-documentation/sds-developer-guide/dev-snapshot/tooling-guide/bamm-cli.html) and in [GitHub](https://github.com/OpenManufacturingPlatform/sds-sdk/releases)
- [ ] use **Camel-Case** (e.g., "MyModelElement" or "TimeDifferenceGmtId", when in doubt follow https://google.github.io/styleguide/javaguide.html#s5.3-camel-case)
- [ ] the identifiers for all model elements **start with a capital letter** except for properties
- [ ] the identifier for **properties starts with a small letter**
- [ ] all model elements **at least contain the fields "preferred name" and "description"** in English language. The description must be comprehensible. It is not required to write full sentences but style should be consistent over the whole model
- [ ] Property and the referenced Characteristic should not have the same name
- [ ] the versioning in the URN **follows semantic versioning**, where minor version bumps are backwards compatible and major version bumps are not backwards compatible. 
- [ ] use **abbreviations only when necessary** and if these are sufficiently common
- [ ] **avoid redundant prefixes in property names** (consider adding properties to an enclosing Entity or even adapt the namespace of the model elements, e.g., instead of having two properties `DismantlerId` and `DismantlerName` use an Entity `Dismantler` with the properties `name` and `id` or use a URN like `io.catenax.dismantler:0.0.1`)
- [ ] fields `preferredName` and `description` are not the same
- [ ] **`preferredName` should be human readable** and follow normal orthography (e.g., no camel case but normal word separation)
- [ ] name of aspect is singular except if it only has one property which is a Collection, List or Set. In theses cases, the aspect name is plural.
- [ ] units are referenced from the BAMM unit catalog whenever possible
- [ ] **use constraints** to make known constraints from the use case explicit in the aspect model 
- [ ] when relying on **external standards**, they are referenced through a **"see"** element
- [ ] all properties with an [simple type](https://openmanufacturingplatform.github.io/sds-documentation/bamm-specification/v1.0.0/datatypes.html) have an example value
- [ ] metadata.json exists with status "release"
- [ ] generated json schema validates against example json payload
- [ ] file RELEASE_NOTES.md exists and contains entries for proposed model changes 
- [ ] all contributors to this model are mentioned in copyright header of model file

## MS3 Criteria
(to be filled out by semantic modeling team before merge to main-branch)
- [ ] All required reviewers have approved this PR (see reviewers section)
- [ ] The new aspect (version) will be implemented by at least one data provider
- [ ] The new aspect (version) will be consumed by at least one data consumer
- [ ] There exists valid test data
- [ ] In case of a new (incompatible) major version to an existing version, a migration strategy has been developed
- [ ] The model has at least version '1.0.0'
- [ ] The release date in the Release Note is set to the date of the MS3 approval

2023-07-10 12:58 UTC, bs-jokri requested changes
please check comments

2023-07-10 12:58 UTC, bs-jokri commented on io.catenax.mp_standard_unsubscribe/1.0.0/UnsubscribeShopfloorInformation.ttl
> +#
# Copyright (c) 2023 Contributors to the Eclipse Foundation

2023-07-10 12:58 UTC, bs-jokri commented on io.catenax.mp_standard_unsubscribe/1.0.0/UnsubscribeShopfloorInformation.ttl
> +@prefix ext-header: <urn:samm:io.catenax.messaging_header:1.0.0#> .
if renaming of messaging_header model is required do not forget to adjust here

2023-07-10 12:58 UTC, bs-jokri commented on io.catenax.mp_standard_unsubscribe/1.0.0/UnsubscribeShopfloorInformation.ttl
> +   samm:preferredName "UnsubscribeShopfloorInformation"@en ;
please use normal orthography and proper noun. For whole model. Will not comment any further occasions

2023-07-10 12:58 UTC, bs-jokri commented on io.catenax.mp_standard_unsubscribe/RELEASE_NOTES.md
> +## [1.0.0]
add date of MS3 approval as soon as it is available

2023-07-13 10:14 UTC, bs-jokri commented
@wehrstedt-jan I understood that this model is not required anymore. If so, could you please close the PR then.

2023-07-19 08:01 UTC, wehrstedt-jan commented
not required anymore

2023-07-19 08:01 UTC, closed without merging