[New Model]: Quality Message Content
eclipse-tractusx/sldt-semantic-models pull request #311
Opened 2023-09-18 14:45 UTC by jonbckr

## Description
Notifications are - in contrast to classical data offers - a way to push data from a sender to a receiver. This model describes the message content for quality investigations and alerts. It contains standardized attributes for message content common across most use cases in CatenaX. It belongs to the same group of aspects as the MessageHeader Aspect Model: io.catenax.shared.message_header

 -->

Closes #305 

## MS2 Criteria
(to be filled out by PR reviewer)
- [ ] the model **validates** with the BAMM SDS SDK in the version specified in the Readme.md of this repository by the time of the MS2 check  (e.g., 'java -jar bamm-cli.jar -i \<path-to-aspect-model\> -v ). The  SAMM CLI is available [here](https://eclipse-esmf.github.io/esmf-developer-guide/tooling-guide/samm-cli.html) and in [GitHub](https://github.com/eclipse-esmf/esmf-sdk/releases/tag/v2.3.1)
- [ ] use **Camel-Case** (e.g., "MyModelElement" or "TimeDifferenceGmtId", when in doubt follow https://google.github.io/styleguide/javaguide.html#s5.3-camel-case)
- [ ] the identifiers for all model elements **start with a capital letter** except for properties
- [ ] the identifier for **properties starts with a small letter**
- [ ] all model elements **at least contain the fields "preferred name" and "description"** in English language. The description must be comprehensible. It is not required to write full sentences but style should be consistent over the whole model
- [ ] Property and the referenced Characteristic should not have the same name
- [ ] the versioning in the URN **follows semantic versioning**, where minor version bumps are backwards compatible and major version bumps are not backwards compatible. 
- [ ] use **abbreviations only when necessary** and if these are sufficiently common
- [ ] **avoid redundant prefixes in property names** (consider adding properties to an enclosing Entity or even adapt the namespace of the model elements, e.g., instead of having two properties `DismantlerId` and `DismantlerName` use an Entity `Dismantler` with the properties `name` and `id` or use a URN like `io.catenax.dismantler:0.0.1`)
- [ ] fields `preferredName` and `description` are not the same
- [ ] **`preferredName` should be human readable** and follow normal orthography (e.g., no camel case but normal word separation)
- [ ] name of aspect is singular except if it only has one property which is a Collection, List or Set. In theses cases, the aspect name is plural.
- [ ] units are referenced from the BAMM unit catalog whenever possible
- [ ] **use constraints** to make known constraints from the use case explicit in the aspect model 
- [ ] when relying on **external standards**, they are referenced through a **"see"** element
- [ ] all properties with an [simple type](https://eclipse-esmf.github.io/samm-specification/2.0.0/datatypes.html) have an example value
- [ ] metadata.json exists with status "release"
- [ ] generated json schema validates against example json payload
- [ ] file RELEASE_NOTES.md exists and contains entries for proposed model changes 
- [ ] all contributors to this model are mentioned in copyright header of model file

## MS3 Criteria
(to be filled out by semantic modeling team before merge to main-branch)
- [ ] All required reviewers have approved this PR (see reviewers section)
- [ ] The new aspect (version) will be implemented by at least one data provider
- [ ] The new aspect (version) will be consumed by at least one data consumer
- [ ] There exists valid test data
- [ ] In case of a new (incompatible) major version to an existing version, a migration strategy has been developed
- [ ] The model has at least version '1.0.0'
- [ ] If a previous model exists, model deprecation has been checked for previous model
- [ ] The release date in the Release Note is set to the date of the MS3 approval

2023-09-18 14:46 UTC, jonbckr commented
modelling_team

2023-09-18 14:48 UTC, jonbckr commented
FYI @BenediktMuellerIML @johannsvarela

2023-09-25 12:57 UTC, bs-jokri requested changes
please check my comments

2023-09-25 12:57 UTC, bs-jokri commented on io.catenax.quality_message_content/1.0.0/QualityMessageContent.ttl
> +# Copyright (c) 2022,2023 BASF SE
why 2022. the first version of the model will be released in 2023?

2023-09-25 12:57 UTC, bs-jokri commented on io.catenax.quality_message_content/1.0.0/QualityMessageContent.ttl
> +#######################################################################
will this be a shared aspect? if so, it should be moved to the namespace io.catenax.shared...

2023-09-25 12:57 UTC, bs-jokri commented on io.catenax.quality_message_content/1.0.0/QualityMessageContent.ttl
> +   samm:preferredName "Catena-X Id Regular Expression"@en ;
there is a shared aspect for uuid. Probably use this one here as well

2023-09-28 09:46 UTC, agg3fe commented on io.catenax.quality_message_content/1.0.0/QualityMessageContent.ttl
> +@prefix uuid : <urn:samm:io.catenax.shared.uuid:1.0.0#> .
please remove the space after uuid. it should be together 'uuid:' and not 'uuid :'

2023-09-28 09:48 UTC, agg3fe commented on io.catenax.quality_message_content/1.0.0/QualityMessageContent.ttl
> +   samm-c:baseCharacteristic :Uuidv4Characteristic ;
you need to use 'uuid' as prefix here. So it would be `uuid:Uuidv4Characteristic`
same for the statement at line below.

2023-09-28 09:48 UTC, agg3fe commented on io.catenax.quality_message_content/1.0.0/QualityMessageContent.ttl
> +:uuid a samm:Property;
and you can remove this property then

2023-09-28 09:50 UTC, agg3fe commented on io.catenax.quality_message_content/1.0.0/QualityMessageContent.ttl
> +@prefix : <urn:samm:org.eclipse.digitaltwin:1.0.0#> .
you can add this prefix also here `@prefix : <urn:samm:io.catenax.quality_message_content:1.0.0#>.`

2023-10-05 11:43 UTC, jonbckr commented
@agg3fe @bs-jokri Pls check MS2, thank you! :)

2023-10-06 14:15 UTC, agg3fe commented on io.catenax.quality_message_content/1.0.0/QualityMessageContent.ttl
> +   samm:description "A text that e.g. describes the quality alert or the quality investigation. Recommendations or counter actions can be added by the receiver when ACCECPTED or DECLINED the notifica
please correct the typo 'ACCEPTED'

2023-10-06 14:18 UTC, agg3fe commented on io.catenax.quality_message_content/1.0.0/QualityMessageContent.ttl
> +   samm:description "The severity of the quality notification describes its criticality. The severity is set by the initiator of a quality notification.\n\nThe following entries are supported and all
I think 'aesthetic' issue would be correct term.

2023-10-06 14:19 UTC, agg3fe commented on io.catenax.quality_message_content/1.0.0/QualityMessageContent.ttl
> +   samm:description "A Unique ID to indentify a serialized part or a batch.\nSee also https://confluence.catena-x.net/x/f6uAAQ\n\nThis is one element in the array.\n\nAn item is added by the initiato
please correct typo 'indentify'

2023-10-09 16:33 UTC, jonbckr commented
@agg3fe thx for your comments, i just fixed them, so you can label it with MS2!

2023-10-10 12:39 UTC, agg3fe approved these changes
LGTM

2023-10-16 14:12 UTC, agg3fe approved these changes
LGTM

2023-10-23 13:59 UTC, agg3fe commented
This model is on Hold for now and waiting for some further clarification.

2023-11-15 16:10 UTC, closed without merging