[New Model]: Software Information 1.0.0
eclipse-tractusx/sldt-semantic-models pull request #320
Opened 2023-09-27 07:16 UTC by johannsvarela

## Description
An ECU and installed software components (versions) form a unit consisting of a hardware component (ECU) and software components for installation in a product (e.g. vehicle). While an ECU as a hardware component has a part number and a serial number, there are not always part numbers and serial numbers for each software component.

This leads to the fact that the creation of digital twins for software components is not useful. A mapping of a unit with an ECU and its installed software components by means of a linkage of digital twins is therefore not possible.

For this reason, the **software must be mapped and documented in a (new) separate aspect model** so that it can be linked to the corresponding digital twin of the ECU.

Closes #314 (old/renamed branch #317)

## MS2 Criteria
(to be filled out by PR reviewer)
- [ ] the model **validates** with the SAMM SDS SDK in the version specified in the Readme.md of this repository by the time of the MS2 check  (e.g., 'java -jar samm-cli.jar aspect \<path-to-aspect-model\> validate ). The  SAMM CLI is available [here](https://eclipse-esmf.github.io/esmf-developer-guide/tooling-guide/samm-cli.html) and in [GitHub](https://github.com/eclipse-esmf/esmf-sdk/releases/tag/v2.3.1)
- [ ] use **Camel-Case** (e.g., "MyModelElement" or "TimeDifferenceGmtId", when in doubt follow https://google.github.io/styleguide/javaguide.html#s5.3-camel-case)
- [ ] the identifiers for all model elements **start with a capital letter** except for properties
- [ ] the identifier for **properties starts with a small letter**
- [ ] all model elements **at least contain the fields "preferred name" and "description"** in English language. The description must be comprehensible. It is not required to write full sentences but style should be consistent over the whole model
- [ ] Property and the referenced Characteristic should not have the same name
- [ ] the versioning in the URN **follows semantic versioning**, where minor version bumps are backwards compatible and major version bumps are not backwards compatible. 
- [ ] use **abbreviations only when necessary** and if these are sufficiently common
- [ ] **avoid redundant prefixes in property names** (consider adding properties to an enclosing Entity or even adapt the namespace of the model elements, e.g., instead of having two properties `DismantlerId` and `DismantlerName` use an Entity `Dismantler` with the properties `name` and `id` or use a URN like `io.catenax.dismantler:0.0.1`)
- [ ] fields `preferredName` and `description` are not the same
- [ ] **`preferredName` should be human readable** and follow normal orthography (e.g., no camel case but normal word separation)
- [ ] name of aspect is singular except if it only has one property which is a Collection, List or Set. In theses cases, the aspect name is plural.
- [ ] units are referenced from the SAMM unit catalog whenever possible
- [ ] **use constraints** to make known constraints from the use case explicit in the aspect model 
- [ ] when relying on **external standards**, they are referenced through a **"see"** element
- [ ] all properties with an [simple type](https://eclipse-esmf.github.io/samm-specification/2.0.0/datatypes.html) have an example value
- [ ] metadata.json exists with status "release"
- [ ] generated json schema validates against example json payload
- [ ] file RELEASE_NOTES.md exists and contains entries for proposed model changes 
- [ ] all contributors to this model are mentioned in copyright header of model file

## MS3 Criteria
(to be filled out by semantic modeling team before merge to main-branch)
- [ ] All required reviewers have approved this PR (see reviewers section)
- [ ] The new aspect (version) will be implemented by at least one data provider
- [ ] The new aspect (version) will be consumed by at least one data consumer
- [ ] There exists valid test data
- [ ] In case of a new (incompatible) major version to an existing version, a migration strategy has been developed
- [ ] The model has at least version '1.0.0'
- [ ] If a previous model exists, model deprecation has been checked for previous model
- [ ] The release date in the Release Note is set to the date of the MS3 approval

2023-09-29 07:49 UTC, johannsvarela commented
@bs-jokri @agg3fe would it be possible to review this PR to get the MS2 approval?

2023-10-02 09:12 UTC, agg3fe commented on io.catenax.software_information/1.0.0/SoftwareInformation.ttl
> +@prefix : <urn:samm:io.catenax.sofware_information:1.0.0#>.
typo in `sofware_information`

2023-10-02 09:21 UTC, agg3fe commented on io.catenax.software_information/1.0.0/SoftwareInformation.ttl
> +   samm:preferredName "Version Trait"@en;
please also add some description here

2023-10-02 09:25 UTC, agg3fe commented on io.catenax.software_information/1.0.0/SoftwareInformation.ttl
> +   samm:description "Describes the sofware components with the most important data(e.g. name, version,..)."@en;
typo in 'sofware'.
please check in all other please also if you find any.

2023-10-02 09:26 UTC, agg3fe commented on io.catenax.software_information/1.0.0/SoftwareInformation.ttl
> +:CatenaXIdTraitCharacteristic a samm-c:Trait;
please provide any preferred name here

2023-10-02 09:37 UTC, agg3fe commented on io.catenax.software_information/1.0.0/SoftwareInformation.ttl
> +:Uuidv4Characteristic a samm:Characteristic;
there is a shared aspect model available for uuidv4. please check on using that, instead of declaring yourself in model.

2023-10-02 09:38 UTC, agg3fe requested changes
please check my comments

2023-10-04 12:26 UTC, johannsvarela commented
> please check my comments

@agg3fe can you review my changes i have made? :)

2023-10-06 14:36 UTC, agg3fe commented on io.catenax.software_information/1.0.0/SoftwareInformation.ttl
> +   samm:description "If a validity period only has a start that means that the period is valid from the start date without a (yet) defined enddate and vice versa."@en;
i think it should be 'end date' and not 'enddate'

2023-10-06 15:36 UTC, johannsvarela commented
> @johannsvarela could you please resolve this small PR comment about typo, and then we should be good for MS2 approval.

@agg3fe done :)

2023-10-23 13:59 UTC, agg3fe commented
This model is on Hold for now and waiting for some further clarification.

2024-03-27 09:07 UTC, johannsvarela commented
> This model is on Hold for now and waiting for some further clarification.

@agg3fe Finally we can continue with the QG process to check and merge this aspect model! :-)

FYI @BenediktMuellerIML

2024-04-08 06:47 UTC, agg3fe commented on io.catenax.software_information/1.0.0/SoftwareInformation.ttl
> +@prefix ext-uuid: <urn:samm:io.catenax.shared.uuid:1.0.0#>.
Can you please uuid 2.0.0 version.
You might need to rebase your branch with main branch.

2024-04-08 06:53 UTC, agg3fe commented on io.catenax.software_information/1.0.0/SoftwareInformation.ttl
> +# Copyright (c) 2023 BASF SE
2024 required now

2024-04-08 06:54 UTC, agg3fe commented on io.catenax.software_information/1.0.0/SoftwareInformation.ttl
> +   samm:description "The software information aspect model contains the essential information of all software components that have been implented or flashed in an instantiated part (e.g. serialized p
typo `implented`

2024-04-10 17:45 UTC, agg3fe commented on io.catenax.software_information/RELEASE_NOTES.md
> +## [1.0.0] 2023-10-02
please change the date to 8 April.

2024-04-11 06:41 UTC, johannsvarela commented on io.catenax.software_information/RELEASE_NOTES.md
> +## [1.0.0] 2023-10-02
@agg3fe Done! :)

2024-04-11 20:17 UTC, merged