[Model Update] Get production forecast 2.0.0
eclipse-tractusx/sldt-semantic-models pull request #553
Opened 2024-01-24 13:22 UTC by FlorianDue

## Description

Message Header and shopfloor_information_types are updated to version 2.0.0updated

 -->

Closes #533 

## MS2 Criteria
(to be filled out by PR reviewer)
- [x] the model **validates** with the SAMM SDS SDK in the version specified in the Readme.md of this repository by the time of the MS2 check  (e.g., 'java -jar samm-cli.jar aspect \<path-to-aspect-model\> validate ). The  SAMM CLI is available [here](https://eclipse-esmf.github.io/esmf-developer-guide/tooling-guide/samm-cli.html) and in [GitHub](https://github.com/eclipse-esmf/esmf-sdk/releases/tag/v2.3.2)
- [x] use **Camel-Case** (e.g., "MyModelElement" or "TimeDifferenceGmtId", when in doubt follow https://google.github.io/styleguide/javaguide.html#s5.3-camel-case)
- [x] the identifiers for all model elements **start with a capital letter** except for properties
- [x] the identifier for **properties starts with a small letter**
- [x] all model elements **at least contain the fields "preferred name" and "description"** in English language. The description must be comprehensible. It is not required to write full sentences but style should be consistent over the whole model
- [x] Property and the referenced Characteristic should not have the same name
- [x] the versioning in the URN **follows semantic versioning**, where minor version bumps are backwards compatible and major version bumps are not backwards compatible. 
- [x] use **abbreviations only when necessary** and if these are sufficiently common
- [x] **avoid redundant prefixes in property names** (consider adding properties to an enclosing Entity or even adapt the namespace of the model elements, e.g., instead of having two properties `DismantlerId` and `DismantlerName` use an Entity `Dismantler` with the properties `name` and `id` or use a URN like `io.catenax.dismantler:0.0.1`)
- [x] fields `preferredName` and `description` are not the same
- [x] **`preferredName` should be human readable** and follow normal orthography (e.g., no camel case but normal word separation)
- [x] name of aspect is singular except if it only has one property which is a Collection, List or Set. In theses cases, the aspect name is plural.
- [x] units are referenced from the SAMM unit catalog whenever possible
- [x] **use constraints** to make known constraints from the use case explicit in the aspect model 
- [x] when relying on **external standards**, they are referenced through a **"see"** element
- [x] all properties with an [simple type](https://eclipse-esmf.github.io/samm-specification/2.0.0/datatypes.html) have an example value
- [x] metadata.json exists with status "release"
- [x] generated json schema validates against example json payload
- [x] file RELEASE_NOTES.md exists and contains entries for proposed model changes 
- [x] all contributors to this model are mentioned in copyright header of model file

## MS3 Criteria
(to be filled out by semantic modeling team before merge to main-branch)
- [x] All required reviewers have approved this PR (see reviewers section)
- [x] The new aspect (version) will be implemented by at least one data provider
- [x] The new aspect (version) will be consumed by at least one data consumer
- [x] There exists valid test data
- [x] In case of a new (incompatible) major version to an existing version, a migration strategy has been developed
- [x] The model has at least version '1.0.0'
- [x] If a previous model exists, model deprecation has been checked for previous model
- [x] The release date in the Release Note is set to the date of the MS3 approval

2024-01-25 12:31 UTC, agg3fe commented on io.catenax.shopfloor_information.get_production_forecast/2.0.0/GetProductionForecast.ttl
> +@prefix samm: <urn:samm:org.eclipse.esmf.samm:meta-model:2.0.0#>.
please change to samm:meta-model:2.1.0

2024-01-25 16:03 UTC, FlorianDue commented
Thank you for your feedback!

I just pushed the latest version and similar to the shopfloor_information_types, I set the samm metamodel to 2.1.0, removed the spaces at the end and set version 1.0.0 to deprecated.

Looking forward to your feedback!

2024-01-26 10:03 UTC, agg3fe commented on io.catenax.shopfloor_information.get_production_forecast/2.0.0/GetProductionForecast.ttl
> +    samm:preferredName "customerId"@en;
preferredName should be human readable and follow normal orthography (e.g., no camel case but normal word separation)

2024-01-26 10:05 UTC, agg3fe requested changes
please check my comments

2024-01-26 10:06 UTC, agg3fe commented
@FlorianDue 
since model conains reference to shopfloorinformationtypes, I would merge this model after the referenced model.

2024-01-26 13:10 UTC, FlorianDue commented
> please check my comments
should be fixed

2024-01-26 13:13 UTC, FlorianDue commented
> @FlorianDue since model conains reference to shopfloorinformationtypes, I would merge this model after the referenced model.
Thank you for your support!

That's fine. We would also like to get MS3 on Monday for these 3 models (#553  #554 and #551) Are there any steps that we have to do? For example create a new issue?

2024-01-26 13:15 UTC, agg3fe approved these changes
LGTM

2024-01-26 13:19 UTC, agg3fe commented
> > @FlorianDue since model conains reference to shopfloorinformationtypes, I would merge this model after the referenced model.
> > Thank you for your support!
> 
> That's fine. We would also like to get MS3 on Monday for these 3 models (#553 #554 and #551) Are there any steps that we have to do? For example create a new issue?

Nothing else is required. We are good for MS3 in next meeting. please make sure someone from your team is there in meeting on Monday to present the model.

2024-01-26 13:22 UTC, FlorianDue commented
Sure, ill be there. See you Monday and have a nice weekend!

2024-01-31 10:01 UTC, merged