[New Model]: Notifications 1.0.0
eclipse-tractusx/sldt-semantic-models pull request #576
Opened 2024-01-29 15:10 UTC by stiwan8020

## Description

The Notification model allows the exchange of alerts between business partners. Alerts can occur on site(s) (e.g. strike, earthquake, fire, flood) which can have an effect on another site(s) (demand-reduction, capacity-reduction, capacity-increase, demand-increase). This model also allows to exchange the affected item numbers and a custom user message.

 -->

Closes #527

## MS2 Criteria
(to be filled out by PR reviewer)
- [ ] the model **validates** with the SAMM SDS SDK in the version specified in the Readme.md of this repository by the time of the MS2 check  (e.g., 'java -jar samm-cli.jar aspect \<path-to-aspect-model\> validate ). The  SAMM CLI is available [here](https://eclipse-esmf.github.io/esmf-developer-guide/tooling-guide/samm-cli.html) and in [GitHub](https://github.com/eclipse-esmf/esmf-sdk/releases/tag/v2.3.2)
- [ ] use **Camel-Case** (e.g., "MyModelElement" or "TimeDifferenceGmtId", when in doubt follow https://google.github.io/styleguide/javaguide.html#s5.3-camel-case)
- [ ] the identifiers for all model elements **start with a capital letter** except for properties
- [ ] the identifier for **properties starts with a small letter**
- [ ] all model elements **at least contain the fields "preferred name" and "description"** in English language. The description must be comprehensible. It is not required to write full sentences but style should be consistent over the whole model
- [ ] Property and the referenced Characteristic should not have the same name
- [ ] the versioning in the URN **follows semantic versioning**, where minor version bumps are backwards compatible and major version bumps are not backwards compatible. 
- [ ] use **abbreviations only when necessary** and if these are sufficiently common
- [ ] **avoid redundant prefixes in property names** (consider adding properties to an enclosing Entity or even adapt the namespace of the model elements, e.g., instead of having two properties `DismantlerId` and `DismantlerName` use an Entity `Dismantler` with the properties `name` and `id` or use a URN like `io.catenax.dismantler:0.0.1`)
- [ ] fields `preferredName` and `description` are not the same
- [ ] **`preferredName` should be human readable** and follow normal orthography (e.g., no camel case but normal word separation)
- [ ] name of aspect is singular except if it only has one property which is a Collection, List or Set. In theses cases, the aspect name is plural.
- [ ] units are referenced from the SAMM unit catalog whenever possible
- [ ] **use constraints** to make known constraints from the use case explicit in the aspect model 
- [ ] when relying on **external standards**, they are referenced through a **"see"** element
- [ ] all properties with an [simple type](https://eclipse-esmf.github.io/samm-specification/2.0.0/datatypes.html) have an example value
- [ ] metadata.json exists with status "release"
- [ ] generated json schema validates against example json payload
- [ ] file RELEASE_NOTES.md exists and contains entries for proposed model changes 
- [ ] all contributors to this model are mentioned in copyright header of model file

## MS3 Criteria
(to be filled out by semantic modeling team before merge to main-branch)
- [ ] All required reviewers have approved this PR (see reviewers section)
- [ ] The new aspect (version) will be implemented by at least one data provider
- [ ] The new aspect (version) will be consumed by at least one data consumer
- [ ] There exists valid test data
- [ ] In case of a new (incompatible) major version to an existing version, a migration strategy has been developed
- [ ] The model has at least version '1.0.0'
- [ ] If a previous model exists, model deprecation has been checked for previous model
- [ ] The release date in the Release Note is set to the date of the MS3 approval

2024-01-31 10:11 UTC, tom-rm-meyer-ISST commented
Checked validation of model. For some reason the shared aspect for bpnl is lookup up in the ttl files directory. Locally running the cli version 2.5.1 works.

2024-02-01 09:12 UTC, stiwan8020 commented
@tom-rm-meyer-ISST problem solved: the namespace of the model was wrong 🤦‍♂️
- @prefix : <urn:samm:org.eclipse.notification:1.0.0#>.
+ @prefix : <urn:samm:io.catenax.notifications:1.0.0#> .

2024-02-01 10:39 UTC, agg3fe commented on io.catenax.notifications/1.0.0/Notifications.ttl
> +@prefix ext-number: <urn:samm:io.catenax.shared.business_partner_number:1.0.0#> .
please use business_partner_number 2.0.0 as it is already released.

2024-02-01 10:39 UTC, agg3fe commented on io.catenax.notifications/1.0.0/Notifications.ttl
> +@prefix ext-uuid: <urn:samm:io.catenax.shared.uuid:1.0.0#> .
here also use uuid2.0.0 model. I have recently released new shared model versions.
Its always better to use the latest models.

2024-02-01 13:43 UTC, agg3fe commented on io.catenax.notifications/1.0.0/Notifications.ttl
> +# Copyright (c) 2023-2024 ISTOS GmbH (a member of the DMG Mori Group)
only 2024 is required

2024-02-01 13:46 UTC, agg3fe commented on io.catenax.notifications/1.0.0/Notifications.ttl
> +   samm:description """The affected Business Partner SITE Numbers of the sending party.
There is unnecessary space in the description. please correct this.
Correct in other places also.

2024-02-01 14:02 UTC, agg3fe requested changes
please check my comments

2024-02-02 10:00 UTC, agg3fe commented on io.catenax.notifications/RELEASE_NOTES.md
> +## [1.0.0]
please add date 2024-02-05, if you want MS3 on next meeting.

2024-02-02 10:00 UTC, agg3fe approved these changes
LGTM

2024-02-15 16:27 UTC, stiwan8020 commented
@agg3fe after a lot of discussions we finally agreed on a common model name. Now the model is ready for the final review

2024-02-19 14:23 UTC, agg3fe approved these changes
LGTM

2024-02-19 15:04 UTC, agg3fe commented
property name change required.
@jacewski-bosch

2024-02-23 10:13 UTC, merged