[New Model]: PartTypeInformation 1.0.0
eclipse-tractusx/sldt-semantic-models pull request #603
Opened 2024-02-05 08:40 UTC by johannsvarela

## Description
..................................................................................................................................................................
This PR replaces the original request to adapt the PartAsPlanned -> #567 
..................................................................................................................................................................

Based on the continous development of the Industry Core, the existing **PartAsPlanned** aspect model will be renamed to **PartTypeInformation**. Therefore a new aspect model is needed, which contains the same functions as the previous PartAsPlanned 2.0.0.

Additionally these new topics will be done within the implementation of the new/renamed aspect model:

- Integration of the new shared Classifcation model (#520)
- Permit to add date information excluding time 
``` 
^(?:[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(?:[.][0-9]+)?Z|[0-9]{4}-[0-9]{2}-[0-9]{2}(?:T[0-9]{2}:[0-9]{2}:[0-9]{2}(?:[.][0-9]+)?(?:Z|[+-][0-9]{2}:[0-9]{2}))?)$
``` 

Closes #591 

## MS2 Criteria
(to be filled out by PR reviewer)
- [ ] the model **validates** with the SAMM SDS SDK in the version specified in the Readme.md of this repository by the time of the MS2 check  (e.g., 'java -jar samm-cli.jar aspect \<path-to-aspect-model\> validate ). The  SAMM CLI is available [here](https://eclipse-esmf.github.io/esmf-developer-guide/tooling-guide/samm-cli.html) and in [GitHub](https://github.com/eclipse-esmf/esmf-sdk/releases/tag/v2.5.1)
- [ ] use **Camel-Case** (e.g., "MyModelElement" or "TimeDifferenceGmtId", when in doubt follow https://google.github.io/styleguide/javaguide.html#s5.3-camel-case)
- [ ] the identifiers for all model elements **start with a capital letter** except for properties
- [ ] the identifier for **properties starts with a small letter**
- [ ] all model elements **at least contain the fields "preferred name" and "description"** in English language. The description must be comprehensible. It is not required to write full sentences but style should be consistent over the whole model
- [ ] Property and the referenced Characteristic should not have the same name
- [ ] the versioning in the URN **follows semantic versioning**, where minor version bumps are backwards compatible and major version bumps are not backwards compatible. 
- [ ] use **abbreviations only when necessary** and if these are sufficiently common
- [ ] **avoid redundant prefixes in property names** (consider adding properties to an enclosing Entity or even adapt the namespace of the model elements, e.g., instead of having two properties `DismantlerId` and `DismantlerName` use an Entity `Dismantler` with the properties `name` and `id` or use a URN like `io.catenax.dismantler:0.0.1`)
- [ ] fields `preferredName` and `description` are not the same
- [ ] **`preferredName` should be human readable** and follow normal orthography (e.g., no camel case but normal word separation)
- [ ] name of aspect is singular except if it only has one property which is a Collection, List or Set. In theses cases, the aspect name is plural.
- [ ] units are referenced from the SAMM unit catalog whenever possible
- [ ] **use constraints** to make known constraints from the use case explicit in the aspect model 
- [ ] when relying on **external standards**, they are referenced through a **"see"** element
- [ ] all properties with an [simple type](https://eclipse-esmf.github.io/samm-specification/2.0.0/datatypes.html) have an example value
- [ ] metadata.json exists with status "release"
- [ ] generated json schema validates against example json payload
- [ ] file RELEASE_NOTES.md exists and contains entries for proposed model changes 
- [ ] all contributors to this model are mentioned in copyright header of model file

## MS3 Criteria
(to be filled out by semantic modeling team before merge to main-branch)
- [ ] All required reviewers have approved this PR (see reviewers section)
- [ ] The new aspect (version) will be implemented by at least one data provider
- [ ] The new aspect (version) will be consumed by at least one data consumer
- [ ] There exists valid test data
- [ ] In case of a new (incompatible) major version to an existing version, a migration strategy has been developed
- [ ] The model has at least version '1.0.0'
- [ ] If a previous model exists, model deprecation has been checked for previous model
- [ ] The release date in the Release Note is set to the date of the MS3 approval

2024-02-05 08:41 UTC, johannsvarela commented
FYI @BenediktMuellerIML @jacewski-bosch @jonbckr

2024-02-05 08:41 UTC, johannsvarela commented
modeling_team

2024-02-05 14:40 UTC, catroest commented on io.catenax.part_type_information/RELEASE_NOTES.md
> +- Initial version of the aspect model PartTypeInformation (formely PartAsPlanned)
typo formely

2024-02-07 14:24 UTC, agg3fe commented on io.catenax.part_type_information/1.0.0/PartTypeInformation.ttl
> +   samm:description "The characteristic of the part site information that represents a set of possible site to a repective part. "@en;
typo `repective`

2024-02-07 14:27 UTC, agg3fe requested changes
please check comments

2024-02-07 14:48 UTC, johannsvarela commented
@catroest @agg3fe Changes were made like requested. Please check my PR again. Thanks! :)

2024-02-07 15:51 UTC, catroest reviewed
Minor spacing and writing mistakes in the descriptions which could be fixed.

2024-02-07 15:51 UTC, catroest commented on io.catenax.part_type_information/1.0.0/PartTypeInformation.ttl
> +   samm:description "Encapsulation for data related to the part type"@en;
missing dot at the end

2024-02-07 15:51 UTC, catroest commented on io.catenax.part_type_information/1.0.0/PartTypeInformation.ttl
> +   samm:description "Part ID as assigned by the manufacturer of the part. The Part ID identifies the part in the manufacturer`s dataspace. The Part ID references a specific version of a part. The ver
is the line break working like this: "\n\nThe"

2024-02-07 15:51 UTC, catroest commented on io.catenax.part_type_information/1.0.0/PartTypeInformation.ttl
> +   samm:description "Name of the part as assigned by the manufacturer"@en;
missing dot at the end

2024-02-07 15:51 UTC, catroest commented on io.catenax.part_type_information/1.0.0/PartTypeInformation.ttl
> +   samm:description "The function of the site in relation to the part(i.e. the activity within the value chain of the part that is performed at the site)"@en;
missing space after part (relation to the **part(i.e.** the activity)
dot at the end of the sentence

2024-02-07 15:51 UTC, catroest commented on io.catenax.part_type_information/1.0.0/PartTypeInformation.ttl
> +   samm:description "Timestamp, from when the site has the specified function for the given part"@en;
missing dot at the end

2024-02-07 15:51 UTC, catroest commented on io.catenax.part_type_information/1.0.0/PartTypeInformation.ttl
> +   samm:description "Timestamp, until when the site has the specified function for the given part"@en;
missing dot at the end

2024-02-07 15:51 UTC, catroest commented on io.catenax.part_type_information/1.0.0/PartTypeInformation.ttl
> +   samm:description "Describes the characteristics of the function for a site related to the respective part"@en;
missing dot at the end

2024-02-07 15:51 UTC, catroest commented on io.catenax.part_type_information/1.0.0/PartTypeInformation.ttl
> +   samm:description "The part ID is a multi-character string, usually assigned by an ERP system"@en;
missing dot at the end

2024-02-07 15:51 UTC, catroest commented on io.catenax.part_type_information/1.0.0/PartTypeInformation.ttl
> +   samm:description "Part Name in string format from the respective system in the value chain"@en;
write "Name" uncapitalized
missing dot at the end

2024-02-07 15:51 UTC, catroest commented on io.catenax.part_type_information/1.0.0/PartTypeInformation.ttl
> +   samm:description "A site is a delimited geographical area where a legal entity does business(geographical address with geo coordinates).A site always has a primary physical address. It is possible
missing space after first sentence

2024-02-12 08:15 UTC, catroest approved these changes

2024-02-12 10:39 UTC, agg3fe approved these changes
LGTM

2024-02-13 11:49 UTC, merged