[Model Update] Digital product passport
eclipse-tractusx/sldt-semantic-models pull request #636
Opened 2024-02-09 14:22 UTC by catroest

## Description
Updates sonform with the latest provisonal agreement or the DIgital Product Passport Regulation:
https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CONSIL:ST_5147_2024_INIT

 -->

Closes #529 

## MS2 Criteria
(to be filled out by PR reviewer)
- [ ] the model **validates** with the SAMM SDS SDK in the version specified in the Readme.md of this repository by the time of the MS2 check  (e.g., 'java -jar samm-cli.jar aspect \<path-to-aspect-model\> validate ). The  SAMM CLI is available [here](https://eclipse-esmf.github.io/esmf-developer-guide/tooling-guide/samm-cli.html) and in [GitHub](https://github.com/eclipse-esmf/esmf-sdk/releases/tag/v2.5.1)
- [ ] use **Camel-Case** (e.g., "MyModelElement" or "TimeDifferenceGmtId", when in doubt follow https://google.github.io/styleguide/javaguide.html#s5.3-camel-case)
- [ ] the identifiers for all model elements **start with a capital letter** except for properties
- [ ] the identifier for **properties starts with a small letter**
- [ ] all model elements **at least contain the fields "preferred name" and "description"** in English language. The description must be comprehensible. It is not required to write full sentences but style should be consistent over the whole model
- [ ] Property and the referenced Characteristic should not have the same name
- [ ] the versioning in the URN **follows semantic versioning**, where minor version bumps are backwards compatible and major version bumps are not backwards compatible. 
- [ ] use **abbreviations only when necessary** and if these are sufficiently common
- [ ] **avoid redundant prefixes in property names** (consider adding properties to an enclosing Entity or even adapt the namespace of the model elements, e.g., instead of having two properties `DismantlerId` and `DismantlerName` use an Entity `Dismantler` with the properties `name` and `id` or use a URN like `io.catenax.dismantler:0.0.1`)
- [ ] fields `preferredName` and `description` are not the same
- [ ] **`preferredName` should be human readable** and follow normal orthography (e.g., no camel case but normal word separation)
- [ ] name of aspect is singular except if it only has one property which is a Collection, List or Set. In theses cases, the aspect name is plural.
- [ ] units are referenced from the SAMM unit catalog whenever possible
- [ ] **use constraints** to make known constraints from the use case explicit in the aspect model 
- [ ] when relying on **external standards**, they are referenced through a **"see"** element
- [ ] all properties with an [simple type](https://eclipse-esmf.github.io/samm-specification/2.0.0/datatypes.html) have an example value
- [ ] metadata.json exists with status "release"
- [ ] generated json schema validates against example json payload
- [ ] file RELEASE_NOTES.md exists and contains entries for proposed model changes 
- [ ] all contributors to this model are mentioned in copyright header of model file

## MS3 Criteria
(to be filled out by semantic modeling team before merge to main-branch)
- [ ] All required reviewers have approved this PR (see reviewers section)
- [ ] The new aspect (version) will be implemented by at least one data provider
- [ ] The new aspect (version) will be consumed by at least one data consumer
- [ ] There exists valid test data
- [ ] In case of a new (incompatible) major version to an existing version, a migration strategy has been developed
- [ ] The model has at least version '1.0.0'
- [ ] If a previous model exists, model deprecation has been checked for previous model
- [ ] The release date in the Release Note is set to the date of the MS3 approval

2024-02-09 14:24 UTC, catroest commented
@agg3fe please check out for MS2 :)

2024-02-09 14:25 UTC, catroest commented
validation fails, as #603 should be merged first

2024-02-14 13:57 UTC, agg3fe commented
@catroest could you please also update your branch with main branch.

2024-02-15 10:26 UTC, agg3fe commented on io.catenax.generic.digital_product_passport/4.0.0/DigitalProductPassport.ttl
> +:HeaderTrait a samm-c:Trait ;
missing `preferredName` and `description`

2024-02-15 10:30 UTC, agg3fe commented on io.catenax.generic.digital_product_passport/4.0.0/DigitalProductPassport.ttl
> +   samm:description "The matrial footprint of the product. This is mentioned in the ESPR provisional agreement from January 9th, 2024 Annex I:\n(ma) the material footprint of the product;\nand define
typo `matrial`

2024-02-15 10:35 UTC, agg3fe commented on io.catenax.generic.digital_product_passport/4.0.0/DigitalProductPassport.ttl
> +:characteristics a samm:Property ;
Property and the referenced Characteristic should not have the same name

2024-02-15 10:46 UTC, agg3fe requested changes
please check my comments

2024-02-16 10:02 UTC, agg3fe approved these changes
LGTM

2024-02-19 14:59 UTC, catroest commented
@agg3fe the two commits are not MS2 relevant:
- the first one adds 3 missing example values
- the second one changes mistakes in the description where ' was translated wrongly to ?

2024-02-21 11:05 UTC, merged