[New Model]: ECU Certificates 1.0.0
eclipse-tractusx/sldt-semantic-models pull request #705
Opened 2024-04-08 11:56 UTC by johannsvarela

## Description
Today, certificates for ECUs need to be provided by first and second tiers to the OEM. This is done by proprietary interfaces with the use of the CSR concept. With this new aspect model, this process should be standardised based on the digital twins in accordance to the industry core. This will enable a data sovereign solution and reduce interfaces.

Closes #701 

## MS2 Criteria
(to be filled out by PR reviewer)
- [ ] the model **validates** with the SAMM SDS SDK in the version specified in the Readme.md of this repository by the time of the MS2 check  (e.g., 'java -jar samm-cli.jar aspect \<path-to-aspect-model\> validate ). The  SAMM CLI is available [here](https://eclipse-esmf.github.io/esmf-developer-guide/tooling-guide/samm-cli.html) and in [GitHub](https://github.com/eclipse-esmf/esmf-sdk/releases/tag/v2.6.0)
- [ ] use **Camel-Case** (e.g., "MyModelElement" or "TimeDifferenceGmtId", when in doubt follow https://google.github.io/styleguide/javaguide.html#s5.3-camel-case)
- [ ] the identifiers for all model elements **start with a capital letter** except for properties
- [ ] the identifier for **properties starts with a small letter**
- [ ] all model elements **at least contain the fields "preferred name" and "description"** in English language. The description must be comprehensible. It is not required to write full sentences but style should be consistent over the whole model
- [ ] Property and the referenced Characteristic should not have the same name
- [ ] the versioning in the URN **follows semantic versioning**, where minor version bumps are backwards compatible and major version bumps are not backwards compatible. 
- [ ] use **abbreviations only when necessary** and if these are sufficiently common
- [ ] **avoid redundant prefixes in property names** (consider adding properties to an enclosing Entity or even adapt the namespace of the model elements, e.g., instead of having two properties `DismantlerId` and `DismantlerName` use an Entity `Dismantler` with the properties `name` and `id` or use a URN like `io.catenax.dismantler:0.0.1`)
- [ ] fields `preferredName` and `description` are not the same
- [ ] **`preferredName` should be human readable** and follow normal orthography (e.g., no camel case but normal word separation)
- [ ] name of aspect is singular except if it only has one property which is a Collection, List or Set. In theses cases, the aspect name is plural.
- [ ] units are referenced from the SAMM unit catalog whenever possible
- [ ] **use constraints** to make known constraints from the use case explicit in the aspect model 
- [ ] when relying on **external standards**, they are referenced through a **"see"** element
- [ ] all properties with an [simple type](https://eclipse-esmf.github.io/samm-specification/2.0.0/datatypes.html) have an example value
- [ ] metadata.json exists with status "release"
- [ ] generated json schema validates against example json payload
- [ ] file RELEASE_NOTES.md exists and contains entries for proposed model changes 
- [ ] all contributors to this model are mentioned in copyright header of model file

## MS3 Criteria
(to be filled out by semantic modeling team before merge to main-branch)
- [ ] All required reviewers have approved this PR (see reviewers section)
- [ ] The new aspect (version) will be implemented by at least one data provider
- [ ] The new aspect (version) will be consumed by at least one data consumer
- [ ] There exists valid test data
- [ ] In case of a new (incompatible) major version to an existing version, a migration strategy has been developed
- [ ] The model has at least version '1.0.0'
- [ ] If a previous model exists, model deprecation has been checked for previous model
- [ ] The release date in the Release Note is set to the date of the MS3 approval

2024-04-08 11:58 UTC, johannsvarela commented
modeling_team

FYI @BenediktMuellerIML

2024-04-16 12:30 UTC, johannsvarela commented
@agg3fe @catroest Since we will urgently need this aspect model (for several internal implementations), we wanted to ask you whether it would be possible to review this PR by Monday 22.04 so that we can get MS2 & MS3 approval next week?

The new aspect model is about information that is needed to validate and certificate an ECU against the encrypted CSR data. For more details have a look at issue #701 or the descriptions within the aspect model. 

FYI @BenediktMuellerIML

2024-04-16 12:50 UTC, catroest requested changes
small changes

2024-04-16 12:50 UTC, catroest commented on io.catenax.certificate_signing_requests/1.0.0/CertificateSigningRequests.ttl
> +   samm:description "The serial number of the assembly part generated by the manufacturer that is used to identifiy the ECU component in a unique way. The subject serial number is identical to the se
typo: identify

2024-04-16 12:50 UTC, catroest commented on io.catenax.certificate_signing_requests/1.0.0/CertificateSigningRequests.ttl
> +   samm:description "The certificate signing requests model contains the essential information needed to request specific certificates for a unique ECU component via a Certificate Signing Request (CS
delete space at the end

2024-04-16 12:50 UTC, catroest commented on io.catenax.certificate_signing_requests/1.0.0/CertificateSigningRequests.ttl
> +   samm:description "Describes one or more Certificate Singing Requests (CSR). Each set entry contains additional information (e.g. subjectCommonName, subjectLocality, etc.) in readable form, which i
delete space at the end

2024-04-16 12:50 UTC, catroest commented on io.catenax.certificate_signing_requests/1.0.0/CertificateSigningRequests.ttl
> +   samm:description "Describes the common name on where the certificate is requested. "@en;
delete space at the end

2024-04-16 12:50 UTC, catroest commented on io.catenax.certificate_signing_requests/1.0.0/CertificateSigningRequests.ttl
> +   samm:description "Provides information about the specific type of the ECU that will be certified. \n\nThe value for the subjectLocality is always the same for an ECU and its attached CSRs, but is
delete space at the end

2024-04-16 12:50 UTC, catroest commented on io.catenax.certificate_signing_requests/1.0.0/CertificateSigningRequests.ttl
> +   samm:description "A CSR (Certificate Signing Request) is a 64-based PEM formatted and encrypted message to request and receive a digital certificate. The CSR validates the information required by
delete space at the end

2024-04-16 12:50 UTC, catroest commented on io.catenax.certificate_signing_requests/1.0.0/CertificateSigningRequests.ttl
> +   samm:description "The serial number of the assembly part generated by the manufacturer that is used to identifiy the ECU component in a unique way. The subject serial number is identical to the se
delete space at the end

2024-04-16 12:50 UTC, catroest commented on io.catenax.certificate_signing_requests/1.0.0/CertificateSigningRequests.ttl
> +:subjectSerialNumber a samm:Property;
should this link or reference through a "see-link" to the serial part aspect?

2024-04-16 13:17 UTC, agg3fe commented on io.catenax.certificate_signing_requests/1.0.0/CertificateSigningRequests.ttl
> +   samm:description "The serial number of the assembly part generated by the manufacturer that is used to identifiy the ECU component in a unique way. The subject serial number is identical to the se
typo `identifiy`

2024-04-16 13:22 UTC, agg3fe requested changes
please check all comments

2024-04-17 08:43 UTC, johannsvarela commented
> please check all comments

@agg3fe @catroest  thanks for your rapid review! :-)  I've made changes as you commented. Please have a look at the adjustments.

2024-04-21 17:51 UTC, agg3fe approved these changes
LGTM

2024-04-23 09:34 UTC, merged