Pull Request Mandatory Dismantling Information
eclipse-tractusx/sldt-semantic-models pull request #779
Opened 2024-09-18 11:13 UTC by florianstern

## Description

Closes https://github.com/eclipse-tractusx/sig-release/issues/758

## MS2 Criteria
(to be filled out by PR reviewer)
- [ ] the model **validates** with the SAMM SDS SDK in the version specified in the Readme.md of this repository by the time of the MS2 check  (e.g., 'java -jar samm-cli.jar aspect \<path-to-aspect-model\> validate ). The  SAMM CLI is available [here](https://eclipse-esmf.github.io/esmf-developer-guide/tooling-guide/samm-cli.html) and in [GitHub](https://github.com/eclipse-esmf/esmf-sdk/releases/tag/v2.9.5)
- [ ] use **Camel-Case** (e.g., "MyModelElement" or "TimeDifferenceGmtId", when in doubt follow https://google.github.io/styleguide/javaguide.html#s5.3-camel-case)
- [ ] the identifiers for all model elements **start with a capital letter** except for properties
- [ ] the identifier for **properties starts with a small letter**
- [ ] all model elements **at least contain the fields "preferred name" and "description"** in English language. The description must be comprehensible. It is not required to write full sentences but style should be consistent over the whole model
- [ ] Property and the referenced Characteristic should not have the same name
- [ ] the versioning in the URN **follows semantic versioning**, where minor version bumps are backwards compatible and major version bumps are not backwards compatible. 
- [ ] use **abbreviations only when necessary** and if these are sufficiently common
- [ ] **avoid redundant prefixes in property names** (consider adding properties to an enclosing Entity or even adapt the namespace of the model elements, e.g., instead of having two properties `DismantlerId` and `DismantlerName` use an Entity `Dismantler` with the properties `name` and `id` or use a URN like `io.catenax.dismantler:0.0.1`)
- [ ] fields `preferredName` and `description` are not the same
- [ ] **`preferredName` should be human readable** and follow normal orthography (e.g., no camel case but normal word separation)
- [ ] name of aspect is singular except if it only has one property which is a Collection, List or Set. In theses cases, the aspect name is plural.
- [ ] units are referenced from the SAMM unit catalog whenever possible
- [ ] **use constraints** to make known constraints from the use case explicit in the aspect model 
- [ ] when relying on **external standards**, they are referenced through a **"see"** element
- [ ] all properties with an [simple type](https://eclipse-esmf.github.io/samm-specification/2.1.0/datatypes.html) have an example value
- [ ] metadata.json exists with status "release"
- [ ] generated json schema validates against example json payload
- [ ] file RELEASE_NOTES.md exists and contains entries for proposed model changes 
- [ ] all contributors to this model are mentioned in copyright header of model file

## MS3 Criteria
(to be filled out by semantic modeling team before merge to main-branch)
- [ ] All required reviewers have approved this PR (see reviewers section)
- [ ] The new aspect (version) will be implemented by at least one data provider
- [ ] The new aspect (version) will be consumed by at least one data consumer
- [ ] There exists valid test data
- [ ] In case of a new (incompatible) major version to an existing version, a migration strategy has been developed
- [ ] The model has at least version '1.0.0'
- [ ] If a previous model exists, model deprecation has been checked for previous model
- [ ] The release date in the Release Note is set to the date of the MS3 approval

2024-10-07 07:19 UTC, florianstern commented
Hi @jSchuetz88, could you please do the review, so we can finish the pull request?

2024-11-06 08:28 UTC, florianstern commented
Hi @jSchuetz88 , could you please do the review, so we can finish the pull request?

2024-12-03 09:50 UTC, stanfaldin commented
@jSchuetz88 you promised to do the checks here ;)

2024-12-10 21:01 UTC, jSchuetz88 requested changes
Hi @florianstern thank you for the contribution (and your patience),

I went through all MS II criteria and made a few minor suggestions based on them.

2024-12-11 10:03 UTC, florianstern commented on io.catenax.mandatory_dismantling/2.0.0/MandatoryDismantling.ttl
> +   samm:characteristic :Text ;
I think that would be fine if you suggest so

2024-12-11 10:06 UTC, florianstern commented on io.catenax.mandatory_dismantling/2.0.0/MandatoryDismantling.ttl
> +   samm:description "A property of the model, named SLI battery."@en ;
SLI can be deleted

2024-12-11 11:18 UTC, jSchuetz88 commented on io.catenax.mandatory_dismantling/2.0.0/MandatoryDismantling.ttl
> +   samm:dataType xsd:string .
```suggestion
:treatmentTechnique a samm:Property ;
   samm:preferredName "Treatment Technique"@en ;
   samm:description "availability of best treatment techniques"@en ;
   samm:characteristic samm-c:Text ;
   samm:exampleValue "Available" .
```

2024-12-11 11:21 UTC, jSchuetz88 commented on io.catenax.mandatory_dismantling/2.0.0/MandatoryDismantling.ttl
> +# Copyright (c) 2023,2024 Contributors to the Eclipse Foundation
```suggestion
# Copyright (c) 2023 ISTOS GmbH (a member of the DMG Mori Group)
# Copyright (c) 2023 Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V. (represented by Fraunhofer ISST)
# Copyright (c) 2023 TRUMPF Werkzeugmaschinen SE + Co. KG
# Copyright (c) 2023 Volkswagen AG
# Copyright (c) 2023 BASF SE
# Copyright (c) 2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
# Copyright (c) 2023 Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V. (represented by Fraunhofer IML)
# Copyright (c) 2023 Henkel AG & Co. KGaA
# Copyright (c) 2023 Mercedes Benz AG
# Copyright (c) 2023 SAP SE
# Copyright (c) 2023 SupplyOn AG
# Copyright (c) 2023 ZF Friedrichshafen AG
# Copyright (c) 2023 CGI Deutschland B.V. & Co. KG
# Copyright (c) 2023 T-Systems International GmbH
# Copyright (c) 2023 Contributors to the Eclipse Foundation
```

I also updated the licence-header, as the TRG has been updated slightly. Only the year of the first contribution is maintained as everything else can be derived from the Github commit log.

2024-12-11 11:34 UTC, jSchuetz88 commented on io.catenax.mandatory_dismantling/2.0.0/MandatoryDismantling.ttl
> +@prefix : <urn:samm:io.catenax.mandatory_dismantling:2.0.0> .
```suggestion
@prefix : <urn:samm:io.catenax.mandatory_dismantling:2.0.0#> .
```

Sorry, my bad. I forgot to add the # at the end.

2024-12-12 13:21 UTC, jSchuetz88 approved these changes
Good to go from my side.

2024-12-12 15:43 UTC, jSchuetz88 approved these changes

2025-02-24 13:44 UTC, merged