Create shared model to host common properties for Q Semantic models
eclipse-tractusx/sldt-semantic-models pull request #803
Opened 2024-12-04 12:55 UTC by TorstenHirsch

## Description

 -->

Closes #

## MS2 Criteria
(to be filled out by PR reviewer)
- [ ] the model **validates** with the SAMM SDS SDK in the version specified in the Readme.md of this repository by the time of the MS2 check  (e.g., 'java -jar samm-cli.jar aspect \<path-to-aspect-model\> validate ). The  SAMM CLI is available [here](https://eclipse-esmf.github.io/esmf-developer-guide/tooling-guide/samm-cli.html) and in [GitHub](https://github.com/eclipse-esmf/esmf-sdk/releases/tag/v2.9.7)
- [ ] use **Camel-Case** (e.g., "MyModelElement" or "TimeDifferenceGmtId", when in doubt follow https://google.github.io/styleguide/javaguide.html#s5.3-camel-case)
- [ ] the identifiers for all model elements **start with a capital letter** except for properties
- [ ] the identifier for **properties starts with a small letter**
- [ ] all model elements **at least contain the fields "preferred name" and "description"** in English language. The description must be comprehensible. It is not required to write full sentences but style should be consistent over the whole model
- [ ] Property and the referenced Characteristic should not have the same name
- [ ] the versioning in the URN **follows semantic versioning**, where minor version bumps are backwards compatible and major version bumps are not backwards compatible. 
- [ ] use **abbreviations only when necessary** and if these are sufficiently common
- [ ] **avoid redundant prefixes in property names** (consider adding properties to an enclosing Entity or even adapt the namespace of the model elements, e.g., instead of having two properties `DismantlerId` and `DismantlerName` use an Entity `Dismantler` with the properties `name` and `id` or use a URN like `io.catenax.dismantler:0.0.1`)
- [ ] fields `preferredName` and `description` are not the same
- [ ] **`preferredName` should be human readable** and follow normal orthography (e.g., no camel case but normal word separation)
- [ ] name of aspect is singular except if it only has one property which is a Collection, List or Set. In theses cases, the aspect name is plural.
- [ ] units are referenced from the SAMM unit catalog whenever possible
- [ ] **use constraints** to make known constraints from the use case explicit in the aspect model 
- [ ] when relying on **external standards**, they are referenced through a **"see"** element
- [ ] all properties with an [simple type](https://eclipse-esmf.github.io/samm-specification/2.1.0/datatypes.html) have an example value
- [ ] metadata.json exists with status "release"
- [ ] generated json schema validates against example json payload
- [ ] file RELEASE_NOTES.md exists and contains entries for proposed model changes 
- [ ] all contributors to this model are mentioned in copyright header of model file

## MS3 Criteria
(to be filled out by semantic modeling team before merge to main-branch)
- [ ] All required reviewers have approved this PR (see reviewers section)
- [ ] The new aspect (version) will be implemented by at least one data provider
- [ ] The new aspect (version) will be consumed by at least one data consumer
- [ ] There exists valid test data
- [ ] In case of a new (incompatible) major version to an existing version, a migration strategy has been developed
- [ ] The model has at least version '1.0.0'
- [ ] If a previous model exists, model deprecation has been checked for previous model
- [ ] The release date in the Release Note is set to the date of the MS3 approval

2024-12-04 13:00 UTC, TorstenHirsch commented
Still in draft

2024-12-09 13:15 UTC, TorstenHirsch commented
@JulianSchererZF

2024-12-12 15:38 UTC, jSchuetz88 requested changes
Hi @theodorisinger,

thank you to clean up the quality aspect models. Unfortunatelly, here is still some work left. Especially regarding the MS II criteria:

>  all model elements at least contain the fields "preferred name" and "description" in English language. The description must be comprehensible. It is not required to write full sentences but style should be consistent over the whole model

2024-12-12 15:39 UTC, jSchuetz88 commented
> Still in draft

I should have read the comments first, sorry! feel free to ignore the review.

2025-01-13 08:27 UTC, TorstenHirsch commented
@jSchuetz88  Please review the file

2025-02-24 15:03 UTC, jSchuetz88 commented
> @JulianSchererZF Hi Julian, this is the first working version of the shared model file.

Hi Torsten, sorry I overlooked the update that this PR is now ready. I will check it in the course of the week.

2025-02-25 09:20 UTC, TorstenHirsch commented
Hi Johann,

I will update the core modell today anyhow -> please check this new version instead of the old one.

Thank you. BG Torsten

Mit freundlichen Grüßen / Best regards

Torsten Hirsch
BD/MSA-IPM7

Mobil +49 162 3972185
​
From: Johann Schütz ***@***.***>
Sent: Monday, February 24, 2025 4:10 PM
To: eclipse-tractusx/sldt-semantic-models ***@***.***>
Cc: Hirsch Torsten (BD/MSA-IPM7 BD/MSA-MQE-Sq4) ***@***.***>; Mention ***@***.***>
Subject: Re: [eclipse-tractusx/sldt-semantic-models] Create shared model to host common properties for Q Semantic models (PR #803)


@JulianSchererZF<https://github.com/JulianSchererZF> Hi Julian, this is the first working version of the shared model file.

Hi @TorstenHirsch<https://github.com/TorstenHirsch>, sorry I overlooked the update that this PR is now ready. I will check it in the course of the week.

—
Reply to this email directly, view it on GitHub<https://github.com/eclipse-tractusx/sldt-semantic-models/pull/803#issuecomment-2678730597>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYLP65ICS6LDFUAWCM22VFT2RMY3BAVCNFSM6AAAAABTADMO56VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMNZYG4ZTANJZG4>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>
[jSchuetz88]jSchuetz88 left a comment (eclipse-tractusx/sldt-semantic-models#803)<https://github.com/eclipse-tractusx/sldt-semantic-models/pull/803#issuecomment-2678730597>

@JulianSchererZF<https://github.com/JulianSchererZF> Hi Julian, this is the first working version of the shared model file.

Hi @TorstenHirsch<https://github.com/TorstenHirsch>, sorry I overlooked the update that this PR is now ready. I will check it in the course of the week.

—
Reply to this email directly, view it on GitHub<https://github.com/eclipse-tractusx/sldt-semantic-models/pull/803#issuecomment-2678730597>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYLP65ICS6LDFUAWCM22VFT2RMY3BAVCNFSM6AAAAABTADMO56VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMNZYG4ZTANJZG4>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2025-02-27 15:28 UTC, TorstenHirsch commented
Hello @jSchuetz88 @JulianSchererZF I updated the model to the latest version -> please check and review. May be we can have a meeting to discuss the results.

2025-03-08 02:19 UTC, jSchuetz88 reviewed
@TorstenHirsch Sorry about the long wait. Overall this model looks good to me. Technically, all MS II criteria are passed. The model as well as the payload validates successfully.

I have two only remarks before approval.

There is the _:plantCatenaXId_ which seems to be the BPNS of the plant. But there are also _:catenaXPartId_, _:catenaXVehicleId_, _:catenaXQualityTaskId_ which are a UUID. For me, the usage of "CatenaXIds" as a prefix seem to be more confusing on the semantic level and less helpful as multiple aspect models currently use the property and prefix in different ways. Is this prefix mandatory?

2025-03-08 02:19 UTC, jSchuetz88 commented on io.catenax.shared.quality_core/1.0.0/QualityCore.ttl
> +   samm:description "As defined in java.time.format.ISO_LOCAL_DATE without timezone."@en ;
Can this be defined in a language-agnostic way?

2025-03-28 06:59 UTC, jSchuetz88 approved these changes
Thank you for including all the changes. LGTM.

2025-04-09 11:37 UTC, TorstenHirsch commented
@jSchuetz88 Any updates on the SC3 topic? I checked all SC2 points as discussed on Monady

2025-04-14 13:07 UTC, jSchuetz88 approved these changes
Thank you for including the changes. LGTM.

2025-04-14 13:31 UTC, stephanbcbauer approved these changes
LGTM ⇾ discussed with @jSchuetz88

2025-04-14 13:31 UTC, merged